spring:
  profiles:
    active: dev
  application:
    name: hr-inventory

server:
  port: 8080

jwt:
  secret_key: ${JWT_SECRET_KEY}
  expires_in_ms: 900000
  refresh_token:
    expires_in_s: 86400

logging:
  level:
    root: INFO
    com.mcyldz.hrinventory: DEBUG